"""Initial schema

Revision ID: ffb0d30ef2c4
Revises: 
Create Date: 2025-10-02 14:08:47.721350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffb0d30ef2c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction_count', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROCESSING', 'COMPLETED', 'FAILED', name='statusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_created', 'analysis_results', ['status', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'analysis_results', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_created_at'), 'analysis_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_status'), 'analysis_results', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_results_user_id'), 'analysis_results', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_analysis_result_id'), 'predictions', ['analysis_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_analysis_result_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_analysis_results_user_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_status'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_created_at'), table_name='analysis_results')
    op.drop_index('idx_user_created', table_name='analysis_results')
    op.drop_index('idx_status_created', table_name='analysis_results')
    op.drop_table('analysis_results')
    # ### end Alembic commands ###
